"""add_claim_status_and_notes

Revision ID: 1234567890ab
Revises: f6a7b8c9d0e1
Create Date: 2026-03-20 00:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1234567890ab"
down_revision: Union[str, None] = "f6a7b8c9d0e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "claim_documents",
        sa.Column(
            "status", sa.String(length=32), server_default="SUBMITTED", nullable=False
        ),
    )
    op.add_column("claim_documents", sa.Column("notes", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("claim_documents", "notes")
    op.drop_column("claim_documents", "status")
    # ### end Alembic commands ###
